### ISSUE TITLE
Error Padding

### ISSUE THREAD

**Issue by Trpaladini** [max1220/lua-bitmap#1]
"I checked your code and found that the padding calculation for images that are not a multiple of 4 was causing an error when calculating the offset. Below is a suggested code to fix it."

-- Check if the width in bytes is already a multiple of 4
if (self.width * Bpp) % 4 == 0 then
    line_w = self.width * Bpp  -- No need for padding
else
    line_w = math.ceil(self.width * Bpp / 4) * 4  -- Adjust to multiples of 4
end

-- Calculate the index for the pixel (no inversion)
local index = self.pixel_offset + y * line_w + x * Bpp

-- If the image is top-down (inverted)
if self.topdown then
    index = self.pixel_offset + (self.height - y - 1) * line_w + x * Bpp
end

**Comment by max1220** [comment]
Thank you for your bug report!
The issue should be fixed now.

Here's the version of the fix I've created.

```lua
local Bpp = self.bpp/8
local row_len = self.width * Bpp -- length of pixel data in bytes
local row_stride = math.ceil(row_len/4)*4 -- padded length of a row in bytes
local index = self.pixel_offset + y*row_stride + x*Bpp
if self.topdown then
	index = self.pixel_offset + (self.height-y-1)*row_stride + x*Bpp
end
```

I've also added a test image where the width is not a multiple of 4.
